
name: 'dbt_project'
version: '1.0.0'
dbt-cloud:
    project-id: 70471823429720
profile: 'dbt_project'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:  
  - "target"
  - "dbt_packages"

models:
  dbt_project:
    staging:
      +schema: staging
      +materialized: table
    mart_marketing:
        +schema: mart_marketing
        +materialized: table