
name: 'dbt_event'
version: '1.0.0'
dbt-cloud:
    project-id: 70471823429720
profile: 'dbt_event'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:  
  - "target"
  - "dbt_packages"

models:
  dbt_event:
    silver:
      +schema: silver
      +materialized: table
    gold:
        +schema: gold
        +materialized: table